packages/yoshi/package.json
packages/yoshi/test/start.spec.js

**Yoshi 3** provides `babel-preset-yoshi`, `babel-preset-wix` that use to be provided, will not be provided through yoshi's dependencies, that's a **Breaking Change**.

remove babel-preset-wix as now we provide babel-preset-yoshi instead

---

CHANGELOG.md

There is no spoon 🥄(nor version 2.5.2)

Fix changelog version typo

---

packages/yoshi/src/require-hooks/ts-node-register.js
packages/yoshi/test/test.spec.js

In order to allow more robust tree shaking & module concat optimisation, we need to enable `module: 'es2015'` in tsconfig.json file, the problem is that node code that was written using es6 import / export syntax will not work with it. So my PR will force `commonjs` for ts-node, at that way, it will ignore the tsconfig flag.
Added test that uses es6 import syntax, enable `es2015` as TS module type, run mocha and check that it is not failed.

feat(ts): Allow work with es2015, commonjs for ts-node

---

packages/yoshi/config/webpack.config.common.js
packages/yoshi/test/build.spec.js

UMD default behavior in Webpack 4 is broken for node:
https://github.com/webpack/webpack/issues/6525
Added a workaround that mimics the Webpack 3 behavior
Creating a UMD bundle and verifying that it runs in node with exit code 0

fix umd behavior in node

---

packages/babel-preset-yoshi/index.js

Change the default presets.modules to 'commonjs' ( babel-preset-yoshi)

Use commonjs as default for preset modules

---

packages/yoshi/package.json

As we moved to the public namespace it worth changing it in the `package.json` repository field.

move repository link to the location of the yoshi repo

---

config/webpack.config.client.js

By default, uglifyJs encodes non ascii characters to Unicode. This breaks in ie11. 
For example "\uD83D\uDCF7" is uglified into this "📷".
"ascii_only: true" flag fixes this problem. There's a small discussion about it here https://github.com/facebook/create-react-app/issues/2488.

uglifyJs encoding non ascii characters for ie11

---

packages/yoshi/package.json
packages/yoshi/src/tasks/petri-specs/index.js
packages/yoshi/test/tasks/petri-specs/petri-specs.spec.js

It's not needed anymore - I removed that task from `petri-specs@1.2.0`.

drop petri-specs convert task

---

README.md
packages/yoshi/config/project.js
packages/yoshi/config/webpack.config.common.js
packages/yoshi/test/build.spec.js

Adds a configuration key to yoshi that enables consumers to sue webpacks resolve.alias
Tested by created a fake modules within `node_modules` and then requiring it using an alias

feat(resolveAlias): added suport for webpack resolve.alias

---

README.md
packages/yoshi/bin/yoshi.js
packages/yoshi/package.json
packages/yoshi/src/commands/release.js

* use version 7 of wnpm ci
* when using with `--minor`, bump the minor version

wnpm ci update

---

packages/eslint-config-yoshi/index.js
packages/eslint-config-yoshi/package.json
packages/tslint-config-yoshi/index.js
packages/tslint-config-yoshi/package.json

Adds the `wix-style-react/no-full-wsr-lib` temporary rule to our lint packages.
This rule fails when importing `wix-style-react` components in a way that imports the entire library (until wsr supports tree shaking).

Add wix-style-react lint rules

---

packages/yoshi/bin/yoshi.js
packages/yoshi/src/commands/test.js

Running yoshi test --jest was missing crucial options that could only be passed as CLI arguments, these are --runInBand and --forceExit.
TBD

Added two cli options when using Jest: runInBand forceExit

---

packages/babel-preset-yoshi/index.js

Fixes #568
We would transpile dynamic import only in tests, this PR change the condition and transpile it only when used in webpack.

do not transpile dynamic imports only when used in webpack

---

packages/create-yoshi-app/templates/client-typescript/.vscode/launch.json
packages/create-yoshi-app/templates/client/.vscode/launch.json
packages/create-yoshi-app/templates/component-library-typescript/.vscode/launch.json
packages/create-yoshi-app/templates/component-library/.vscode/launch.json
packages/create-yoshi-app/templates/fullstack-typescript/.vscode/launch.json
packages/create-yoshi-app/templates/fullstack/.vscode/launch.json
packages/create-yoshi-app/templates/node-library-typescript/.vscode/launch.json
packages/create-yoshi-app/templates/node-library/.vscode/launch.json
packages/create-yoshi-app/templates/server-typescript/.vscode/launch.json
packages/create-yoshi-app/templates/server/.vscode/launch.json
packages/create-yoshi-app/templates/universal-typescript/.vscode/launch.json
packages/create-yoshi-app/templates/universal/.vscode/launch.json

This PR fixes the generated `launch.json` for debugging with vscode for all templates. This uses jest when available in the template or just `yoshi test` otherwise.
N/A

fix generated launch.json for vscode across templates

---

packages/yoshi/src/tasks/cdn/server-api.js
packages/yoshi/src/webpack-utils.js

This PR matches the functionality of the experimental start with the current one.

Redirect `.min` assets to non min assets in start-app

---

package.json
packages/babel-preset-yoshi/package.json
packages/bootstrap-hot-loader/package.json
packages/create-yoshi-app/scripts/e2e.js
packages/create-yoshi-app/src/constants.js
packages/create-yoshi-app/src/utils.js
packages/create-yoshi-app/src/verifyRegistry.js
packages/create-yoshi-app/src/verifyWorkingDirectory.js
packages/eslint-config-yoshi-base/package.json
packages/eslint-config-yoshi/package.json
packages/jest-environment-yoshi-bootstrap/package.json
packages/jest-environment-yoshi-puppeteer/package.json
packages/jest-yoshi-preset/package.json
packages/tslint-config-yoshi-base/package.json
packages/tslint-config-yoshi/package.json
packages/yoshi-angular-dependencies/package.json
packages/yoshi-config/package.json
packages/yoshi-helpers/package.json
packages/yoshi-style-dependencies/package.json
packages/yoshi/package.json
verdaccio.yaml

This PR changes how our E2E tests install the dependencies of generated projects.
Instead of installing dependencies and then copying/linking the version of Yoshi/others, it creates a local npm registry and publishes the entire monorepo to it. It then installs all dependencies from that local registry to mimic the tree as much as possible.

Improve e2e tests by emulating production installations

---

packages/yoshi/config/webpack.config.storybook.js

Storybook started using short names for css module classes, this changes them back to long names. Looks like a typo as the block below uses debug true.
...

Change isDebug to true in the storybook styleloaders

---

docs/guides/babel-setup.md
docs/guides/jest-setup.md
website/sidebars.json

Yoshi's documentation website should be the one place to look for all documentation related to Yoshi (and related ecosystem). The website is also searchable which makes its content much easier to find.
This PR adds `babel-preset-yoshi`'s and `jest-yoshi-preset`'s docs to the website.

Move the docs for babel-preset-yoshi and jest-yoshi-preset to the docs website

---

packages/yoshi/config/webpack.config.js

If you're using a client project with a fake server, it doesn't make sense to put your fake server in `src`. This PR will look for a 2nd entry if the 1st one wasn't found.
__Note that this is specifically for the experimental server bundle.__

Look for a fake-server entry if the standard server entry isn't found

---

packages/jest-environment-yoshi-puppeteer/globalSetup.js

Currently, we merge the user's options for Puppeteer with some defaults. Users that passes `devtools: true` expect the browser to be opened, but because we always pass `headless: true` the browser stays close.
This PR removes the `headless` default (which already defaults to `true` in Puppeteer) to make those configurations predictable.

Remove headless: true default from puppeteer.launch call

---

packages/jest-environment-yoshi-puppeteer/package.json

Add [globby](https://github.com/sindresorhus/globby) as a dependency.
This PR fixes an issue where globalSetup of `jest-environment-yoshi-puppeteer` failed to setup  puppeteer environment because it used an old version of `globby` that was install by other dependency of the project.

Add globby as dependency

---

packages/yoshi/test/build.spec.js
packages/yoshi/test/config.spec.js
packages/yoshi/test/e2e.spec.js
packages/yoshi/test/jasmine.spec.js
packages/yoshi/test/lint.spec.js
packages/yoshi/test/loaders.spec.js
packages/yoshi/test/start.spec.js
packages/yoshi/test/test.spec.js
packages/yoshi/test/webpack-config.spec.js
test-helpers/test-phases.js

This is something I used locally instead of adding verbose to tests I want to debug. It will output the execution logs if the tests fails, making it unnecessary to push again with `.verbose` to see the logs on the CI on a failing test.
**A Gotcha**: Some of our tests cases (`it`) share the same test (`test = tp.create()`) which means that multiple test cases that fail on the same test will both print the output of the same execution. I couldn't find a better way to do it with `mocha`'s `after` hook, because I can access the status of tests there. But I don't know if that gotcha is a deal breaker.

Log test execution output if the test failed

---

packages/jest-environment-yoshi-puppeteer/globalSetup.js
packages/yoshi/test/test.spec.js

Fixes issues with puppeteer tests. Makes the puppeteer setup use the default options for the forward proxy and merges them with user defined args.
Should fix current tests.

Merge user defined puppeteer args with default args

---

packages/yoshi/config/webpack.config.storybook.js
packages/yoshi/test/webpack-config-storybook.spec.js

This PR uses yoshi's webpack node lib mocks config in storybook's webpack config.
Closes #864  
Check that the default configuration is present in storybook's config.

Use webpack node lib mock config in storybook config

---

packages/yoshi/config/webpack.config.js
packages/yoshi/test/webpack-config.spec.js

This adds the ability to check if the bundle is minified or not and by that to consume the proper assets.
For example, in `bundle.min` to point to `styles.min.css`.
The minified bundle should have `process.env.IS_MINIFIED === true` otherwise `process.env.IS_MINIFIED === false`

Add process.env.IS_MINIFIED.

---

packages/yoshi/config/webpack.config.js
packages/yoshi/package.json
test/projects/kitchensink-javascript/integration/loaders.test.js
test/projects/kitchensink-javascript/src/components/features/assets/svg-inclusion.css
test/projects/kitchensink-javascript/src/components/features/svg-inclusion-css.js
test/projects/kitchensink-javascript/src/components/features/svg-inclusion.js
test/projects/kitchensink-typescript/integration/loaders.test.js
test/projects/kitchensink-typescript/src/components/features/assets/svg-inclusion.css
test/projects/kitchensink-typescript/src/components/features/svg-inclusion-css.tsx
test/projects/kitchensink-typescript/src/components/features/svg-inclusion.tsx

Use `svg-url-loader` for requiring svg files.
Used `iesafe: true` as we still need to support IE...

svg-url-loader (#822)

---

packages/yoshi-helpers/utils.js

Original issue:
We had such file `mocha-setup.js`.
```
require('some-not-exsisting-file.js);
...other mocha configuration
```
Inside the yoshi we are cheking if file exsist using function `tryRequire`. If the error code is `MODULE_NOT_FOUND` we don't throw error anymore and just skip this file. In case `mocha-setup.js` require a file which doesn't exist yoshi doesn't produce any errors.
The fix is checking only required file.  The issue was discussed with Artem Yavorskyi.
There are not tests here because I found onle two tests which located at `yoshi-helpers`.

Fix checking if file is exist.

---

packages/create-yoshi-app/templates/business-manager-module-typescript/README.md
packages/create-yoshi-app/templates/business-manager-module-typescript/{%packagejson%}
packages/create-yoshi-app/templates/business-manager-module/README.md
packages/create-yoshi-app/templates/business-manager-module/{%packagejson%}

This PR makes sure that the Business Manager generators open the correct url on `npm start`
Merge only after #1166
Closes #1157

Business Manager template opens correct url on `npm start`

---

packages/yoshi/config/wallaby-jest.js

So there is no more `component` test environment in yoshi 4. Just changed it to the actual one.

Wrong displayName in jest wallaby

---

packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/app/App.js
packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/app/App.st.css
packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/app/appController.js
packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/settingsPanel/SettingsPanel.js
packages/create-yoshi-app/templates/out-of-iframe/javascript/{%packagejson%}

Following todays meeting, I thought there were a few changes that should be made to the OOI generator:
1. The new docs state that using `wix-ui-tpa` is a must, so I thought it would be best to change the `wix-ui-core` button that was used to the `wix-ui-tpa` button (commit [3bc8abf](https://github.com/wix/yoshi/commit/3bc8abfe9ea277b19f808195f4cb60bd12837649)).
2. After adding the `wix-ui-tpa` button, I thought it would be nice to show how the component's styling can be changed from the settings panel (commit [b9f2d76](https://github.com/wix/yoshi/commit/b9f2d7600dec3155b1a72ed21c3f9e78543f72df))
3. It was stated today that `pageReady` returns a promise so maybe it should be `async` by default? Not sure about this... (commit [6031d4e](https://github.com/wix/yoshi/commit/6031d4e00c9abd2f1ff …

OOI generator best practices

---

docs/migration/version-4.md
packages/jest-yoshi-preset/constants.js
packages/jest-yoshi-preset/jest-preset.js

background:
In Yoshi 4, there is no longer an env called `component`, yet projects migrating from Yoshi 3 might not know this, and set `MATCH_ENV=component`. 
If they do, jest is run with no configuration at all, and get a long and meaningless list of errors.
solution:
1) If no env is matched
- configure Jest to not run any test.
- Print a meaningful error to the console
2) Add a note to the migration docs

handle bad MATCH_ENV

---

packages/yoshi/package.json

After generating `fullstack` project via CYA and installing dependencies with `npm`, I had an error trying to run `jest`/`yoshi test`.
To reproduce this issue:
- You need to have global jest dependency below 23 version (it's not resolving .js configs and only json)
- You need to install dependencies via `npm` (yarn tries to move everything to the root until conflicts found).
- call `npx jest` or `npx yoshi test`
*You can't reproduce this issue if you don't have jest installed globally at all or version is >= 23*.
After you `npm install` deps for just generated project, you have a structure like:
```
└─┬ jest
└── jest-cli
```
Then calling `npx jest` will run the binary fail from the `node_modules/.bin/jest`, which will call `jest-cli/bin/jest`.
`jest-cli/bin/jest` contains …

Add jest-cli as a direct yoshi dependency.

---

packages/yoshi/src/tasks/cdn/index.js

Log a full path to the cdn instead of only the port. example:
Running cdn on {port_number} => Running cdn on http://localhost:{port_number}

Log full URL to CDN, including scheme and port

---

packages/yoshi/config/webpack.config.js

This PR configures Webpack to resolve symlinked modules to their symlinked location (instead of the location of the symlink).
Will add more info in a bit.

Resolve symlinks to their symlinked locations in Webpack

---

packages/yoshi/src/commands/start-app.js

fixed issue 1180 https://github.com/wix/yoshi/issues/1180
For now browser always opens app with http protocol

issue-1180: removed https for opening browser

---

packages/jest-environment-yoshi-puppeteer/globalTeardown.js
packages/yoshi/config/hot.js
packages/yoshi/package.json
packages/yoshi/src/commands/start-app.js
packages/yoshi/src/server-process.js
packages/yoshi/src/socket-server.js

This PR attempts to fix a problem where some users don't start their server in the same process their `--server` is running. Instead, they spawn additional processes from that process that then start their server.
This is a problem with how server HMR works because it requires communication between Yoshi and the server bundle. Yoshi has to be the parent of the process that's running the server for it to work.
Instead of relying on IPC communication, this PR replaces it with web sockets so no matter how many processes are between Yoshi and the server, communication still works.

Use sockjs instead of ipc for server HMR communication

---

packages/create-yoshi-app/templates/out-of-iframe/javascript/__tests__/e2e/viewerApp.e2e.js
packages/create-yoshi-app/templates/out-of-iframe/javascript/src/viewerApp/viewerApp.js
packages/create-yoshi-app/templates/out-of-iframe/javascript/{%packagejson%}
packages/create-yoshi-app/templates/out-of-iframe/typescript/__tests__/e2e/viewerApp.e2e.ts
packages/create-yoshi-app/templates/out-of-iframe/typescript/src/viewerApp/viewerApp.tsx
packages/create-yoshi-app/templates/out-of-iframe/typescript/{%packagejson%}

This PR modifies `ooi` templates to start work on production when running `npm start`.
It sends the users (via the `url` flag) to a site that @gileck and myself created, which points to the `localhost`.
It runs an e2e test against production.
I've also changed the `viewerWidget` name into `viewerApp` for terminology sake.
We still need to find solutions for `editorApp` and `settingsPanel`.

work against production when running npm start

---

packages/yoshi/config/webpack.config.js
packages/yoshi/src/commands/start-app.js
packages/yoshi/src/webpack-utils.js

allowing HMR over production site
currently we replace assets in production sites in order to live test our features\bugs.
for that we use either [requestly](https://chrome.google.com/webstore/detail/requestly-redirect-url-mo/mdnleldcmiljblolnjhpnblkcekpdkpa?hl=en) or [clientspecmap experiments](https://bo.wix.com/client-spec-map-experiment-server/experiments/specs.stores.ProductWidgetOOI_local/1380b703-ce81-ff05-f115-39571d94dfcd) or [pacman extension](https://chrome.google.com/webstore/detail/wix-statics-override/fhaehbcdbkccakpjgokgppjkggkmkmbl)
when we enable yoshi's HMR those hacks doesn't work, because the bundled asset first tries to establish web socket to the site it's requested from
I configured webpack dev server to establish the websocket to the local CDN …

allow hmr over production site

---

packages/create-yoshi-app/README.md
packages/create-yoshi-app/__tests__/__fixtures__/fake-template/typescript/template.txt
packages/create-yoshi-app/__tests__/__snapshots__/generateProject.spec.js.snap
packages/create-yoshi-app/__tests__/createApp.spec.js
packages/create-yoshi-app/__tests__/generateProject.spec.js
packages/create-yoshi-app/scripts/e2e.js
packages/create-yoshi-app/src/TemplateModel.js
packages/create-yoshi-app/src/getQuestions.js
packages/create-yoshi-app/src/getValuesMap.js
packages/create-yoshi-app/templates/business-manager-module/javascript/pom.xml
packages/create-yoshi-app/templates/business-manager-module/typescript/pom.xml
packages/create-yoshi-app/templates/client/javascript/pom.xml
packages/create-yoshi-app/templates/client/typescript/pom.xml
packages/create-yoshi-app/templates/fullstack/javascript/pom.xml
packages/create-yoshi-app/templates/fullstack/typescript/pom.xml
packages/create-yoshi-app/templates/library/javascript/pom.xml
packages/create-yoshi-app/templates/library/typescript/pom.xml
packages/create-yoshi-app/templates/out-of-iframe/javascript/pom.xml
packages/create-yoshi-app/templates/out-of-iframe/typescript/pom.xml
packages/create-yoshi-app/templates/server/javascript/pom.xml
packages/create-yoshi-app/templates/server/typescript/pom.xml
test-helpers/fixtures.js
test/projects/kitchensink-javascript/pom.xml
test/projects/kitchensink-typescript/pom.xml

This PR fixes #1334
Removes the `"organization"` field from:

feat(create-yoshi-app): remove organization form wizard and pom.xml

---

packages/yoshi/src/commands/release-monorepo.js

This should cut off some time that PR CI spends fetching `tar.gz` files from `npm` when it's not needed.

Run wnpm-ci prepareForRelase() only in master CI

---

packages/create-yoshi-app/__tests__/verifyRegistry.spec.js
packages/create-yoshi-app/src/utils.js
packages/create-yoshi-app/src/verifyRegistry.js

Today when a user run `npx create-yoshi-app` we check if Wix Private Registry was configured. This validation is not good enough because there is a case which the user doesn't connect to the VPN and this registry isn't reachable. At this PR we check if the user is inside the VPN by making an HTTP request to Wix Private Registry.  
Created unit tests for verifyRegistry module

Update verifyRegistry to check if Wix private registry is reachable (#1403)

---

docs/api/cli.md

Add docs for the new `--server` cli option, an alias to `--entry-point`, which supported only by the new app flow.
Also, update the default value of `--entry-point` option to be ***index.js***

server cli option docs

---

packages/create-yoshi-app/src/utils.js

Since #1419, PR CI doesn't run template tests against the changes in a particular PR and instead run them against `latest`. This PR is a quick fix to make sure we don't see red PRs as green.

Install published version on templates tests rather than latest

---

package.json

`lint-staged` is running eslint without the configuration of `--max-warnings 0` that we have on ci.
It makes lint fail on ci while locally it is passing (when there are only warnings)
This PR makes it so it will fail on warnings during commit hook

make lint-staged to fail on warnings

---

docs/api/cli.md
packages/yoshi/bin/yoshi-cli.js
packages/yoshi/src/commands/start.js
packages/yoshi/test/start.spec.js

Support the `--https` option(an alias for `--ssl`) in `start` command(in addition to `start-app`).
Closes #1126 (`--server` won't be implemented at this point, since it collides with `--no-server`)

support '--https' cli option in 'start' command

---

packages/yoshi/package.json
packages/yoshi/src/verify-dependencies.js

When yoshi finds a dependency with a different major version, it fails and prints an error with the dependency's name and version. 
This case can be confusing if for example the dependency located in an upper folder(such as`~`). 
In order to give a better visibility, yoshi will print the dependency's full path as well.
Closes #1321

print full path of dependencies with different major version

---

.travis.yml

Pretty straight-forward: This PR adjusts our `.travis.yml` to how we recently split our testing commands. Currently Travis is failing because the scripts it calls don't exist anymore.

Adjust travis config to recent split in test commands

---

packages/create-yoshi-app/templates/out-of-iframe/javascript/README.md
packages/create-yoshi-app/templates/out-of-iframe/typescript/README.md

It seems that those links have changed.
This PR fixes them

Fix links to out-of-iframe docs on their templates readme

---

packages/babel-preset-yoshi/index.js

Currently in development mode, we transpile the browser code to very old browsers even though everyone develops on the latest chrome (or other evergreen browser). This makes development harder. First it adds more transpilation than needed in development which is time wasted, and the more important thing it makes debugging much harder, cause the transpilation makes the breakpoints much harder to work with and it changes some of the variables names so it's hard to inspect them.
Transpiling to latest chrome should be our default for development builds.
@ranyitz - I showed these problems to @ronami and we saw that this solution works great (for my use case). But he also mentioned that this was tried in the past and reverted. Do you know something about it?
Not sure, @ronami got a suggestion?

transpile development bundle to last chrome version

---

packages/yoshi/config/webpack.config.js

**Issue no 1:**
In current configuration, the test for `experimentalBuildHtml` is done according to root yoshi config, which means that (in monorepo) we either have  `experimentalBuildHtml` for the whole monorepo, or not. 
We want to be able to configure the `HtmlWebpackPlugin` for a specific package in our monorepo.
**Solution:** 
I changed the test for the flag to use `app`, and not `rootApp`.
**Issue no 2:**
In current configuration, `experimentalBuildHtml` will only work if we have a `templates` folder (otherwise we get an error). We want to be able to use `HtmlWebpackPlugin` capabilities even if we do not have templates in our project. 
**Solution:**
I added a `exists(app.TEMPLATES_DIR)` check for the whole templates part.

Fix HtmlWebpackPlugin to work inside monorepo

---

packages/yoshi-helpers/src/utils.ts

When running build (Storybook/Yoshi) in `editor-elements` mono-repo, `babel-loader` transpiles `node_modules`, causing issues (e.g Storybook doesn't start with 
`Error: exports is not defined` in the browser) and slowing the build.
The issue is caused due to the specific solution made for TB-App.

Editor Elements fix - Transpile node-modules only for TB App

---

packages/yoshi-common/src/webpack.config.ts

@ronami and myself run into an issue when bundled server code (thunderbolt-becky) in target `web` and using isomorphic-unfetch which has `browser` entry in its package.json
...

fix| ignore browser mainField when target:node

---

packages/yoshi-common/src/utils/suricate.ts

A small fix to make the link that is printed to the console clickable, when using suricate. Using `@` makes the link not fully clickable, so replaced with `_`.
...

replace @ with _ in tunnel ids

---

packages/yoshi-flow-monorepo/package.json
packages/yoshi-flow-monorepo/src/webpack.config.ts
yarn.lock

Currently, [Webpack's stats](https://webpack.js.org/configuration/stats) are created only during `yoshi build` and written into `target/webpack-stats.json`.
Going forward, we want to use Webpack's stats to optimize SSR'd responses and this requires writing it during both (`yoshi build`), CI build and local development (`yoshi start`). On top of it, emitting it into `dist/statics` instead of `target` makes sense as it would make it available to see and debug projects that have been deployed. It also makes sense as we write all of Webpack's output to `dist/statics` and having this one exclusion is only confusing.
To not break any existing projects that count on the stats being emitted to the current folder, and to see that always writing stats, without an explicit `--stats` opt-in, this PR …

Generate `stats.json` during build and start into `dist/statics`

---

packages/yoshi-common/src/webpack.config.ts

There is a (small) bug in `notExternalModules` regex patterns. When the user project's name contains, for example, `yoshi-server-test`, we will get a match for  `yoshi-server`, which will cause unwanted bundled dependencies.
Adding `node_modules` to the start will fix this issue.

Fix a bug in notExternalModules regex patterns

---

.npmrc
renovate.json

Since we moved to working with `yarn`, the root `.npmrc` is no longer relevant and can be deleted

Remove .npmrc

---

renovate.json

Closes #1297
This is a very old issue, it was fixed and released on https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/CHANGELOG.md#070-2019-05-27

remove the restriction from mini-css-extract-plugin

---

packages/yoshi-server/src/server.ts
test/javascript/features/yoshi-server/route-default/route-default.test.js
test/javascript/features/yoshi-server/route-default/src/component.js
test/javascript/features/yoshi-server/route-default/src/routes/index.js
test/typescript/features/yoshi-server/route-default/route-default.test.js
test/typescript/features/yoshi-server/route-default/src/component.tsx
test/typescript/features/yoshi-server/route-default/src/routes/index.ts

fixes #1535
We want to be able to have a default route (`/`), which will be mapped to a default file. In this case, I used the following mapping:
`/` -> `routes/index.js`
** My implementation was a naive one (tdd...):
```
route: routePath === '/index' ? '/' : routePath,
```
We can discuss if there's a better way of doing this

`yoshi-server` handle default route

---

.gitignore
docs/guides/jest-setup.md
packages/jest-yoshi-preset/jest-preset.js
packages/yoshi-config/src/jest/config.ts
packages/yoshi-config/src/jest/validConfig.ts
test/javascript/features/jest-preset-overrides/jest-yoshi.config.js
test/javascript/features/jest-preset-overrides/src/component.js
test/javascript/features/jest-preset-overrides/src/component.spec.js
test/javascript/features/jest-preset-overrides/src/moduleToMock.js
test/typescript/features/jest-preset-overrides/jest-yoshi.config.js
website/versioned_docs/version-4.x/guides/jest-setup.md

Allow overriding jest `resetMocks` configuration via `jest-yoshi.config.js` in `specOptions`
Tests are validate that mocks are reseting between tests.

jest-preset-override - allow resetMocks config override

---

packages/create-yoshi-app/templates/out-of-iframe/typescript/{%packagejson%}

I don't see any usages for it and I think it's just being generated for each new project.
`wix-ui-tpa` is the right library to consume "stage" components and it's already included in the generator

[create-yoshi-app][out-of-iframe] - remove wix-ui-core dependency

---

packages/jest-yoshi-preset/jest-preset.js
packages/jest-yoshi-preset/transforms/babel-yoshi-server.js
packages/jest-yoshi-preset/transforms/babel.js
packages/jest-yoshi-preset/transforms/typescript-yoshi-server.js
packages/jest-yoshi-preset/transforms/typescript.js

In e2e tests, we do not want the Yoshi Server Jest transform to be applied on our server production code (It will happen in cases that server code is running on the same process as Jest). 
This PR fixes this issue.

Yoshi Server:don't apply Yoshi Server Jest Transform in e2e tests

---

packages/create-yoshi-app/templates/out-of-iframe/javascript/__tests__/e2e-setup.js
packages/create-yoshi-app/templates/out-of-iframe/javascript/src/viewerApp/viewerApp.e2e.js
packages/create-yoshi-app/templates/out-of-iframe/typescript/__tests__/e2e-setup.ts
packages/create-yoshi-app/templates/out-of-iframe/typescript/src/viewerApp/viewerApp.e2e.ts

Unfortunately sometimes 10 seconds is not enough for viewer to load `<h2>`.
Let's increase timeout for waitForSelector for Viewer App e2e test.

fix(create-yoshi-app): Increase timeout time for h2 selector for viewer.

---

packages/yoshi-flow-monorepo/src/webpack.config.ts

This is needed specifically to support analyzing the webworker output with `webpack-bundle-analyzer` or similar tools. This PR adds this change specifically for monorepo-flow.

Emit Webpack stats file for worker compilation

---

packages/yoshi/types.d.ts

This PR removes `stylable` `st.css` types from yoshi types.
They were added in https://github.com/wix/yoshi/pull/2010 but I think that they are not specifically related to the change in the PR.
The reason of the removal is many breaking changes that were introduced.
See this thread for more information - https://wix.slack.com/archives/CAL591CDV/p1582788739069300
_________________
We can create a separate PR and add it to yoshi types if needed.

Remove stylable runtime from types.d.ts

---

test/typescript/features/stylable/separate-css/src/external-types.d.ts
test/typescript/features/stylable/separate-css/src/test-types.d.ts
test/typescript/features/stylable/separate-css/tsconfig.json

This PR adds a module declaration for `*.st.css` files, specifically for the relevant feature typescript test (the type was reverted as part of https://github.com/wix/yoshi/pull/2024).
Without this declaration, the imported module would be typed as regular `*.css` [definition](https://github.com/wix/yoshi/blob/75485d6029/packages/yoshi/types.d.ts#L85) which leads to the value mismatches.

fix stylable type mismatches

---

test/typescript/features/serve/monorepo/package.json

We have the following warning when running our integration tests:
```
jest-haste-map: Haste module naming collision: serve-monorepo-js
[17:03:00][npm run test:integration:others:js]   The following files share their name; please adjust your hasteImpl:
[17:03:00][npm run test:integration:others:js]     * <rootDir>/javascript/features/serve/monorepo/package.json
[17:03:00][npm run test:integration:others:js]     * <rootDir>/typescript/features/serve/monorepo/package.json
```

Change integration package name to avoid haste map warning

---

packages/yoshi-flow-legacy/bin/yoshi-cli.js

Show the ability to test specific files using `yoshi tests [file]...` in the CLI reference. (when running `yoshi test --help`)
All tests should pass

make `yoshi test --help` show how to run specific test files

---

packages/yoshi-flow-editor/docs/DEV_CENTER_REGISTRATION.md
packages/yoshi-flow-editor/docs/EDITOR-AND-SETTINGS-APPS.md
packages/yoshi-flow-editor/docs/OVERVIEW.md

This is a first iteration of our docs. We are going to store it in docs during active stage of development the flow, but then move it to separate website or Wix Docs.
I would really love to hear some feedback about 2 parts:
- How we should group it (dev center is separate, editor apps is separate with links to it from general overview like big wikipedia articles)
- As we discussed, control docs on our side for generators is a good idea. I would really like to have really basic info for templates + link to normal docs on our side. For example, OVERVIEW.md. Let me know if it sounds bad.
We've also added `Troubleshooting new app registration` section and going to use this link for people, who are facing some issues with new dev center.
Ask few people to follow it and register new apps using …

Add docs for overview and dev center registration + troubleshooting.

---

test/javascript/features/stylable/separate-css/separate-css.test.ts
test/scripts.ts
test/typescript/features/stylable/separate-css/separate-css.test.ts

fixes #2086. 
After a short debugging of this, I believe that the problem is that the test takes  ~23 -24 sec, when the timeout is 25 sec. I increased the timeout and had ~20 CI runs with no flakiness.

Integration tests: try to fix stylable flaky test

---

packages/yoshi-flow-editor-runtime/src/EditorAppWrapper.tsx
packages/yoshi-flow-editor-runtime/src/WidgetWrapper.tsx
packages/yoshi-flow-editor/src/webpack.config.ts
packages/yoshi-flow-editor/src/wrappers/templates/ComponentWidgetEntry.ts

This PR contains fixes and enhancements for styling:
- Use `withStyles` wrapper for viewer and editor entries.
- Always separate css.
- Remove `<link />` from widget.

[yoshi-editor-flow]: Use withStyles wrapper and always separate css

---

.eslintrc
packages/create-yoshi-app/__tests__/verifyNodeVersion.test.ts
packages/eslint-config-yoshi-base/index.js
packages/yoshi-common/src/dev-environment.ts
packages/yoshi-common/src/print-build-results.ts
packages/yoshi-common/src/server-process.ts
packages/yoshi-common/src/storybook/storybook-worker.ts
packages/yoshi-config/src/normalize.ts
packages/yoshi-flow-app/src/webpack.config.ts
packages/yoshi-flow-bm/src/createFlowBMModel.ts
packages/yoshi-flow-bm/src/webpack.config.ts
packages/yoshi-flow-editor/src/webpack.config.ts
packages/yoshi-flow-library/src/commands/start.ts
packages/yoshi-flow-library/src/webpack.config.ts
packages/yoshi-flow-monorepo/src/verify-typescript-references.ts
packages/yoshi-flow-monorepo/src/webpack.config.ts
packages/yoshi-server-react/src/hooks.ts
scripts/build.ts
scripts/customPublish.ts

We are using many `!` in our codebase, I feel that having the `eslint` above is not what we prefer to do.
Lint is passing

disable no null assertion rule in yoshi's codebase

---

docs/getting-started/usage.md

The current command described in the docs to run tests in watch mode (`npm test --watch`) is not working since npm is not passing the `--watch` flag to yoshi.

Fixing the test watch command

---

packages/yoshi-common/src/typescript/run-babel.ts

Having a watch mode that fails and exits on errors is a very bad thing.
This PR fixes a problem where the `watch` mode during `yoshi-library start` would just exit if there was a parsing error from `babel`. (The `cjs` directory)
Now in case there is a parsing error it will be logged but not throw an error. This is by all means not a perfect solution.
In most cases the same parsing error would be raise by both TypeScript and Babel and the TypeScript message will override the one from babel. In extreme cases when something won't work properly only in the `babel` transpilation you would see the error and then be able to recreate it on build.
This is less than ideal, and we need to play with it and see what we should do with it:
1. Maybe show the output of both?
2. Show the output of `babel` …

[Flow library]: Do not exit when there is a babel parsing error during start

---

packages/create-yoshi-app/templates/server/javascript/{%packagejson%}.json
packages/create-yoshi-app/templates/server/typescript/{%packagejson%}.json

Update the `express` version in the server templates to `^4.17.0`.
- to fit the minimal version required by the Node Platform (Slack: https://wix.slack.com/archives/C0C89GRRB/p1585817764395300)
- to align with `fullstack` templates as well - https://github.com/wix/yoshi/blob/master/packages/create-yoshi-app/templates/fullstack/javascript/%7B%25packagejson%25%7D.json#L36
Also yoshi users complained: https://wix.slack.com/archives/CAL591CDV/p1585924513108000

server templates: update express version

---

docs/guides/jest-setup.md
packages/jest-yoshi-preset/jest-preset.js
packages/yoshi-config/src/jest/config.ts
packages/yoshi-config/src/jest/validConfig.ts
test/javascript/features/jest-preset-overrides/__tests__/jest-preset-overrides.e2e.js
test/javascript/features/jest-preset-overrides/jest-yoshi.config.js

Adding the option to override the `globals` object in `e2eOptions`
Added a test to check the existence of a mocked property within the `global` object

add the option to override the `globals` object in `e2eOptions` (#2102)

---

packages/create-yoshi-app/templates/fullstack/javascript/{%packagejson%}.json
packages/create-yoshi-app/templates/fullstack/typescript/{%packagejson%}.json

For some reason the version for `bootstrap-hot-loader` in the generators is 3.X. 
This causes a typing issue when working with `async` for your server code (we added this support in V4)
```
export default hot(module, async (app: Router, context) => {
```

Generators: bump `bootstrap-hot-loader` to V4

---

packages/yoshi-flow-editor/src/commands/build.ts
packages/yoshi-flow-editor/src/webpack.config.ts

Not sure why it's not included, but it's really good to verify nothing unexpected included in the bundle

Add `isAnalyze` option to Worker bundles for flow editor.

---

packages/yoshi-flow-editor-runtime/src/react/SDK/SDKContext.ts
packages/yoshi-flow-editor-runtime/src/react/SDK/SDKRenderProp.tsx

We want to load children in render prop with editorSDK, after it's already fetched, so this is just type enhancement.
Settings.ts
```diff
<EditorSDK>{sdk =>
-  sdk.editorSDK && sdk.editorSDKConfig ? <Settings editorSDK={sdk.editorSDK} /> : null
+ <Settings editorSDK={sdk.editorSDK} />
}</EditorSDK>
```

Use `EditorSDKLoadedContext` interface for editorSDK render prop.

---

packages/yoshi-common/src/utils/should-transpile-file.ts
packages/yoshi-common/src/webpack.config.ts

Currently, [https://github.com/wix-incubator/carmi](Carmi) outputs ES6 code. If/when we decide to run Carmi code on the browser, we'll have to either transpile its output with another tool or improve Carmi's capabilities so that it can output code for different targets (ES5).
Since we currently only run it on the server, this PR stops processing its output with Babel/Typescript which lowers the build/start times significantly (as its output is **very** large).

Don't transpile Carmi's output with Typescript/Babel

---

packages/yoshi-flow-editor/src/wrappers/templates/CommonEditorScriptEntry.ts
packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonEditorScriptEntry.test.ts.snap

Platform can accept function for editorScript which will return object.
The problem here is that, it's not accepting ES6 Modules. So we can take advantage of using wrappers.
For example both options for editor.app.ts will be valid:
```
export default () => {
return {
pageReady() {}
...
}
}
```
```
export const pageReady = fn;
```

Update editor entry-point to accept `default` export with function

---

packages/yoshi-common/src/webpack-dev-server.ts

This will ensure `hmr` will work when developing locally and working on production platforms with the new domain.
> Create.editorx.com (Editor)
> Manage.editorx.com (BizMgr)
> editorx.com (Marketing)
> username.editorx.io (Free Sites)

Add editorx domains to webpack-dev-server's allowed hosts

---

packages/yoshi-server-testing/src/index.ts
test/javascript/features/yoshi-server/api-client-server-react/src/components/App/App.spec.js
test/javascript/features/yoshi-server/api-client-server/src/component.spec.js
test/typescript/features/yoshi-server/api-client-server-react/src/components/App/App.spec.tsx
test/typescript/features/yoshi-server/api-client-server/src/component.spec.tsx

Reverts wix/yoshi#2180
Reverting: this one ran with no updated master tests, which broke master tests...
I'll fix that and have a new PR

Revert "Update yoshi server testing with new api"

---

packages/yoshi-common/src/webpack.config.ts
packages/yoshi-server-client/src/index.ts
test/javascript/features/yoshi-server/api-client-server-react/src/client.js
test/javascript/features/yoshi-server/bm-route/package.json
test/javascript/features/yoshi-server/bm-route/src/client.js
test/javascript/features/yoshi-server/bm-route/src/server.js
test/typescript/features/yoshi-server/api-client-server-react/src/client.tsx
test/typescript/features/yoshi-server/bm-route/package.json
test/typescript/features/yoshi-server/bm-route/src/client.tsx

We want the default baseUrl to be `/_api/<packageName>`, so it will fit the business manager convention.

Yoshi Server: add a Business Manager default baseUrl

---

packages/yoshi-flow-bm-runtime/src/moduleParams.ts
packages/yoshi-flow-bm-runtime/tsconfig.esm.json

I worried so much about adding a second typescript build for our runtime that I completely forgot to actually make it build ESM! 🤣 
Also, forgot to re-export `useModuleParams`.

Fix yoshi-flow-bm-runtime ESM build and root exports

---

packages/yoshi-common/src/webpack.config.ts
packages/yoshi-config/src/config.ts
packages/yoshi-config/src/normalize.ts
packages/yoshi-config/src/validConfig.ts
packages/yoshi-flow-app/src/webpack.config.ts
packages/yoshi-flow-monorepo/src/webpack.config.ts

This should help with:
https://jira.wixpress.com/projects/FEDINF/issues/FEDINF-1094
Like any other externals (webworkerExternals/externals) we will let the user configure it because they are changing according to the app/platform.
Thunderbolt's server (which downloads thunderbolt-elements) needs to verify those externals are located in the node_modules directory.
We are currently not supporting different types of externals in array, but it's pretty ok for start and not sure a lot of user's using it like this.
Will open a follow-up PRs to `thunderbolt-elements`, `editor-elements-library` and `thunderbolt-app`

Allow configuring serverExternals

---

packages/yoshi-helpers/src/utils.ts

Followed the instructions in the [FED onboarding program](https://github.com/Akrabut/fed-crash-course/tree/master/exercises/client-tdd) and `npx jest --watch` failed to run with error:
```
● Test suite failed to run
A different process (/Users/orh/Desktop/FED) is already running on port '3200', aborting.
```
Folder name is 'FED Training' and everything past the first whitespace was ignored.
This happens because `awk '{print $9}'` treats everything after said whitespace as 10th column.
1. `create-yoshi-app` in folder with whitespaces in name.
2. `npm start`.
3. `npx jest --watch` with any puppeteer tests.
`awk '{print substr($0, index($0,$9))}'` takes all text from 9th column to end of the line ($0).

fix 'a different process is already running on port 3200' error when root folder has whitespace

---

packages/create-yoshi-app/templates/business-manager-module/javascript/environment.js
packages/create-yoshi-app/templates/business-manager-module/typescript/environment.js

We want to run the node-platform testkit as a fork, for several reasons. One of them is that we do not want our production code, which runs during e2e tests, to pass via jest transformers.

Yoshi Server, BM generator: run testkit as fork

---

packages/create-yoshi-app/scripts/e2e.js

Currently it's a bug when you have mono-language template (Editor, BM, library), we are running tests 2 times. It's not updating anything except test title and just increasing our CI process time.
cc @amitdahan @ranyitz

Prevent running template tests twice for single-language templates

---

packages/yoshi-flow-monorepo/src/build.ts

Ignore snapshots files during the sync
NOTE: this fix is for monorepo-flow, but it seems like it should be done for the rest flows.

Ignore snapshot files when copying assets in monorepo flow

---

packages/yoshi-flow-monorepo/serve.d.ts

Typing `module.exports` as `default` is wrong
Usage in Thunderbolt with `@ts-check` leads to an error:
I changed it locally and it works:

Type `serve.d.ts` correctly

---

packages/yoshi-flow-editor-runtime/src/viewerScript.ts

We need to pass appData as an object, but not promise. It will be more convenient, since initAppForPage is already a promise

await for initAppForPage result.

---

packages/create-yoshi-app/templates/flow-editor-platform/typescript/src/components/{each%flowData.components:name%each}/viewer.controller.ts
packages/yoshi-flow-editor/src/model.ts
packages/yoshi-flow-editor/src/wrappers/commonViewerScriptWrapping.ts
packages/yoshi-flow-editor/src/wrappers/templates/CommonViewerScriptEntry.ts
packages/yoshi-flow-editor/src/wrappers/templates/__tests__/CommonViewerScriptEntry.test.ts
packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonViewerScriptEntry.test.ts.snap

For platform apps, the id that you get in the `controllerConfigs` map is actually the `controllerType` which is defined on the `AppController` / `AppWidget` data.
this change will enable you to also keep the id that the widget gets from dev center, and also define the controller type that should be used in order to load the script.
This is useful for BoB widgets, since we need the dev center id to install the widget on stage in the editor script like here:
https://github.com/wix-private/bob-bootstrap/blob/master/src/editor/appInstaller.ts#L30
But the id needed in order for the correct script to load is a different id
https://github.com/wix-private/bob-bootstrap/blob/master/src/components/speakers/.component.json#L2
With this change, I could keep the id and the controllerType in …

Allow to set `controllerType` for component configuration

---

jest.config.js
jest.unit.config.js
package.json
packages/jest-yoshi-preset/jest-preset.js
packages/yoshi-flow-legacy/config/jest.config.js
packages/yoshi-flow-legacy/package.json
packages/yoshi-flow-library/package.json
yarn.lock

`jest-teamcity` has support for concurrent test reporting and is actively maintained.
This should be a drop-in replacement, therefore no need for new tests

Replace jest-teamcity-reporter with jest-teamcity

---

packages/yoshi-flow-editor/src/__tests__/utils.test.ts
packages/yoshi-flow-editor/src/model.ts
packages/yoshi-flow-editor/src/wrappers/commonEditorScriptWrapping.ts
packages/yoshi-flow-editor/src/wrappers/commonViewerScriptWrapping.ts
packages/yoshi-flow-editor/src/wrappers/editorAppWrapping.ts
packages/yoshi-flow-editor/src/wrappers/templates/CommonEditorScriptEntry.ts
packages/yoshi-flow-editor/src/wrappers/templates/CommonViewerScriptEntry.ts
packages/yoshi-flow-editor/src/wrappers/templates/ControllerEntryContent.ts
packages/yoshi-flow-editor/src/wrappers/templates/EditorAppEntryContent.ts
packages/yoshi-flow-editor/src/wrappers/templates/WidgetViewerScriptEntry.ts
packages/yoshi-flow-editor/src/wrappers/templates/__tests__/CommonEditorScriptEntry.test.ts
packages/yoshi-flow-editor/src/wrappers/templates/__tests__/CommonViewerScriptEntry.test.ts
packages/yoshi-flow-editor/src/wrappers/templates/__tests__/EditorAppEntryContent.test.ts
packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonEditorScriptEntry.test.ts.snap
packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/CommonViewerScriptEntry.test.ts.snap
packages/yoshi-flow-editor/src/wrappers/templates/__tests__/__snapshots__/EditorAppEntryContent.test.ts.snap
packages/yoshi-flow-editor/src/wrappers/widgetViewerScriptWrapping.ts

Currently, we are asking users to have `viewer.app.ts` and `editor.app.ts`.
Moreover, we are throwing an exception if no `viewer.app.ts` exists. Even if it's empty, user still should have it.
If user will remove `editor.app.ts` it will work, but on the editor website the error will appear (won't break the app, but anyway)
This PR provides a change to make this files optional on user's side. We will still generate a viewerScript and editorScript bundles, but w/o anything except stuff we provide by default - automatic `createControllers`.

Make viewer.app.ts and editor.app.ts optional

---

packages/yoshi-common/package.json
packages/yoshi-common/src/telemetry.ts
packages/yoshi-common/src/webpack.config.ts
website/docs/development/debugging.md
website/docs/development/environment-variables.md
website/sidebars.js
yarn.lock

There are some logs that we always want to see in case of debugging. I believe that we think about those places when writing the code and that it makes sense that it will be easy to see those verbose logs in those situations.
I added the "debug yoshi" section which is an intent the yoshi team have, but also others that just work with it and want to debug it and understand what is the problem.
Debugging a non working telemetry :)

improve debugging guide and added debug mode - initial version

---

packages/create-yoshi-app/src/TemplateModel.ts
packages/create-yoshi-app/src/auto-release/setupAutoRelease.ts
packages/create-yoshi-app/src/createApp.ts
packages/create-yoshi-app/src/dev-center-registration/auth.ts
packages/create-yoshi-app/src/dev-center-registration/getQuestions.ts
packages/create-yoshi-app/src/dev-center-registration/runPrompt.ts
packages/create-yoshi-app/src/extended-prompts.ts
packages/create-yoshi-app/src/generateProject.ts
packages/create-yoshi-app/src/index.ts
packages/create-yoshi-app/src/utils.ts
packages/create-yoshi-app/templates/flow-editor/typescript/fedops.json
packages/create-yoshi-app/templates/flow-editor/typescript/{%packagejson%}.json
packages/yoshi-flow-editor/package.json
packages/yoshi-flow-editor/src/cli.ts
packages/yoshi-flow-editor/src/commands/add-component/fedops.ts
packages/yoshi-flow-editor/src/commands/add-component/index.ts
packages/yoshi-flow-editor/src/commands/add-component/runPrompt.ts
packages/yoshi-flow-editor/src/model.ts
packages/yoshi-flow-editor/src/utils.ts
website/docs/editor-flow/cli-API.md
website/docs/editor-flow/getting-started.md
website/docs/editor-flow/local-development.md

Implementation of the adding a component part from the RFC: https://github.com/wix/yoshi/issues/2520
Currently, we are bootstrapping almost everything needed for development and release with create-yoshi-app for editor flow:
- Generating a basic Widget, controller and Settings
- Dev Center registration for widgets
- configuring sentry
- sled tests for each component
- fedops configuration
- basic experiments bootstrap
- auto-release for current relevant project structure
And it's working like a magic for structure created via `create-yoshi-app`.
In case of new components added, some features will be missed for it under the hood b/c of lack of configuration. It's happening only from the project bootstrap.
This PR solves it with new `add` command. It will open wizard with 3 options:
`Add a …

New CLI Command for editor flow: add

---

packages/yoshi-flow-monorepo/package.json
packages/yoshi-flow-monorepo/src/webpack.config.ts
packages/yoshi-helpers/src/queries.ts
yarn.lock

This PR adds integration with Sentry by uploading [source maps](https://docs.sentry.io/platforms/javascript/sourcemaps) while running in master CI.
This is currently somewhat experimental and enabled specifically for Thunderbolt. I used `process.env.ARTIFACT_VERSION` to tag the release with a unique build number. Sentry injects a global `SENTRY_RELEASE` variable which is checked in [Sentry's client](https://github.com/getsentry/sentry-javascript/blob/d4a9c065c4d8be8107c28e67944addc4386fc81c/packages/browser/src/sdk.ts#L83). This will add the version tag to errors and link them with the matching source maps.

Upload source maps to sentry

---

packages/yoshi-flow-bm-runtime/package.json
packages/yoshi-flow-bm-runtime/src/experiments.tsx
yarn.lock

Experiments are ready for consumption in pages & exported-components.
This is purely an internal change.
Spoke with @Gongreg about accessing experiments in module-level code (`moduleInit`, or in methods), sounds like it isn't necessarily the desired best-practice, so we'll leave this out for now.

Simplify experiments using `scope` prop in flow-bm

---

packages/yoshi-flow-bm-runtime/src/wrapComponent.tsx

We chose to take `moduleParams` from root page/component's props and place it in Context for easy access.
Since we use BM's `BusinessManagerModule.registerPageComponent` and `BusinessManagerModule.registerComponentWithModuleParams` to register pages & components, we're getting the `moduleParams` (and additional undocumented props like `router` and `routeBaseName`) at the root of our page/component.
This makes it harder for us to isolate the `moduleParams` from the component's actual props (exported-components can have props ofc, which are joined together in the `props` object).
To do this right I chose to manually "pick" keys out of the root's props, and construct the `moduleParams` object (passed through Context) only with known fields.
This will mean we now depend on BM's type (and our …

Fix extra renders caused by wrapComponent

---

packages/yoshi-config/src/validConfig.ts

Currently, everyone that uses the `resolveAlias` feature (either for the standard one or the new `webworker.resolveAlias`) gets warnings from `jest-validate` that it's not an unknown option:
This PR marks it correctly so it's an object with arbitrary keys for `jest-validate` so these redundant warnings are no longer appearing.

Remove resolveAlias warnings from jest-validate

---

packages/yoshi-helpers/src/utils.ts

`getProjectArtifactVersion` used `as string`, when it should be actually returning `string | undefined`; 
- removed the `as string`
- fixed the place where we use it

Internal: fix typing problem

---

packages/yoshi-flow-monorepo/src/scripts/start.ts

Current error message is:
Could not find an app with the name of `editor-elements-library` but it exists at the `Apps found:`
Error message with this PR is:

monorepoflow – remove stripOrganization from the error logs

---

packages/yoshi-flow-monorepo/src/scripts/build.ts
packages/yoshi-flow-monorepo/src/webpack.config.ts

This PR reverts #2609 and re-applies #2568. It looks like if we minify while keeping the original function names Carmi will emit enough information to help understand errors without needing source maps.
If it doesn't work we'll revert yet again.
cc @gileck

Remove sourcemaps from site-assets node

---

packages/yoshi/config/wallaby-common.js

Running Wallaby.js in our generator projects, outputs the following logs:
```
wallaby.js started
core v1.0.806
console.log: 
console.log: Multiple setup files were detected:
console.log: 
console.log:  > __tests__/spec-setup.js
console.log:  > __tests__/spec-setup.ts
console.log: 
console.log: We recommend removing one of them. Currently using __tests__/spec-setup.js.
console.log: 
console.log: PASS spec src/components/App/App.spec.js
Finished executing 1 affected test(s) in 12.42 second(s)
```
Wallaby was transpiling `spec-setup.ts` in-place, next to the source file, which made yoshi complain (but not fail).

Let wallaby know not to build `spec-setup.ts`

---

packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/index.js

When there is no response on the request payload the `requestfinished` event breaks
[Slack](https://wix.slack.com/archives/CAL591CDV/p1593689270186900)

fix: requestfinished event -> check for response

---

packages/babel-preset-yoshi/index.js

After discussion with @ranyitz , this adds support for deprecated decorators proposal. This is required by Contacts, that uses Mobx, in order to be able to migrate to Yoshi 4
...

Deprecated Legacy Decorators Support

---

packages/yoshi-flow-bm-runtime/src/createModule.ts
packages/yoshi-flow-bm-runtime/src/types.ts
packages/yoshi-flow-bm/src/constants.ts
packages/yoshi-flow-bm/src/model.ts
packages/yoshi-flow-bm/src/module.ts
website/versioned_docs/version-4.x/business-manager-flow/overview.md
yarn.lock

Closes #2650.
This changes the `src/moduleInit` + `default` export convention for reacting to the module's `init` lifecycle hook to use named exports inside `src/module.ts`.
`src/module.ts`:
```typescript
import { ModuleInitFn, ModuleConfigFn } from 'yoshi-flow-bm-runtime';
export const init: ModuleInitFn = ({ module, moduleParams }) => {
// ...
};
export const config: ModuleConfigFn = (
{ module, moduleParams },
sourceModuleId,
payload,
) => {
// ...
};
```

Add module lifecycle hooks (`init`, `config`) to BM Flow

---

package.json
packages/create-yoshi-app/scripts/e2e.js
packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/cdnProxy.js
packages/jest-yoshi-preset/jest-environment-yoshi-puppeteer/globalSetup.js
packages/yoshi-common/src/webpack-utils.ts
packages/yoshi-common/src/webpack.config.ts
packages/yoshi-flow-legacy/config/protractor.conf.js
packages/yoshi-flow-legacy/test/config.spec.js
packages/yoshi-flow-legacy/test/test.spec.js
packages/yoshi-flow-legacy/test/webpack-config.spec.js
packages/yoshi-flow-monorepo/src/webpack.config.ts
packages/yoshi-helpers/package.json
packages/yoshi-helpers/src/queries.ts
packages/yoshi-helpers/src/utils.ts
packages/yoshi-server-tools/src/serverless-publish.ts
packages/yoshi-serverless-testing/src/index.ts
scripts/utils/constants.ts
test-helpers/env-variables.js
test-helpers/test-phases.js
test/javascript/features/env-vars/env-vars.test.ts
test/scripts.ts
test/typescript/features/env-vars/env-vars.test.ts
test/typescript/features/monorepo/basic.test.ts
test/typescript/features/monorepo/serve.test.ts
test/typescript/features/yoshi-server/api-client-serverless/api-client-serverless.test.ts
test/typescript/features/yoshi-server/serverless-api-error-message/serverless-api-error-message.test.ts
yarn.lock

This PR replaces the current implementation which has knowledge about internal CI implementation details.
We now use the new `ci-build-info` library, that supports both current CI and Falcon CI, so there's no need to have that knowledge inside Yoshi.
Tests were sometimes tricky, since when running locally they behave in one way, and in CI behave in another way (due to the env pollution of CI env vars). I fixed it where possible (forced local env simulation).
cc @ranyitz

Use the ci-build-info library

---

packages/create-yoshi-app/templates/flow-bm/typescript/.module.json
packages/create-yoshi-app/templates/flow-bm/typescript/__tests__/e2e/app.e2e.ts
packages/create-yoshi-app/templates/flow-bm/typescript/src/assets/locale/messages_de.json
packages/create-yoshi-app/templates/flow-bm/typescript/src/assets/locale/messages_en.json
packages/create-yoshi-app/templates/flow-bm/typescript/src/pages/index.scss
packages/create-yoshi-app/templates/flow-bm/typescript/src/pages/index.tsx
packages/create-yoshi-app/templates/flow-bm/typescript/translations/de.json
packages/create-yoshi-app/templates/flow-bm/typescript/translations/en.json
packages/yoshi-flow-bm-runtime/package.json
packages/yoshi-flow-bm-runtime/src/i18n.tsx
packages/yoshi-flow-bm-runtime/src/index.ts
packages/yoshi-flow-bm-runtime/src/wrapComponent.tsx
packages/yoshi-flow-bm/src/component.ts
packages/yoshi-flow-bm/src/config/normalize.ts
packages/yoshi-flow-bm/src/config/types.ts
packages/yoshi-flow-bm/src/config/validConfig.ts
packages/yoshi-flow-bm/src/constants.ts
packages/yoshi-flow-bm/src/queries.ts
website/versioned_docs/version-4.x/business-manager-flow/overview.md
yarn.lock

Adds a way to opt-in to i18n integration.
By adding the following config to `.module.json`:
```json
{
"translations": {
"default": "en"
}
}
```
Your pages & components will be wrapped with an initialized `<I18nextProvider />` (thanks @vybu 🥇!) to be consumed as follows:
```typescript jsx
import { useTranslation } from 'yoshi-flow-bm-runtime';
export default () => {
const [t] = useTranslation();
return <div>{t('translation.key')}</div>;
};
```
Translation files will be loaded by convention from `src/assets/locale/messages_{LOCALE}.json`.
Note: 
I enabled Suspense by default. I'm open to hear opinions.
It's on by default for `@wix/wix-experiments-react` so I wanted to match that.
```json
{
"translations": {
"default": "en",
"suspense": false
}
}
```
Will disable it.

Add `@wix/wix-i18n-config` integration to BM flow

---

packages/yoshi-common/package.json
packages/yoshi-common/src/@stylable/manifest-plugin.ts
packages/yoshi-common/src/webpack.config.ts
yarn.lock

- Add support for StylableManifestPlugin
- Allows working with stylable-loader 
- We want to support dynamic imports in stylable using `stylable-loader` (this is a blocker for migrating any more components using Stylable in Thunderbolt) 
- When we use `stylable-loader`, we lose the abillity to use StylableMetadata plugin which is crucial both for integration with the StylablePanel in the editor, and with applying customisations in the Viewer (Thunderbolt in this case) 
- StylableManifestPlugin supplies a way to collect all information about a stylesheet and package structure needed to support both the Editor and Viewer integrations. (outputs a JSON which is used by Viewer / Editor) 
- To support "per component" loading and gather the information, StylableManifestPlugin filters and collect …

Support stylable manifest plugin [EXPERIMENTAL_STYLABLE_LOADER]
