wix/yoshi

packages/yoshi/src/commands/test.js
packages/yoshi/src/tasks/app-server/index.js
packages/yoshi/src/tasks/protractor/index.js

Enable support 0 (auto debug port generation) for --debug and --debug-brk flags

enable debug with auto port generator

---

packages/yoshi/config/protractor.conf.js

adding support for exclude field in protractor.conf.js
conf file.. not sure hot to test

protractor.conf.js - add support for exclude

---

packages/yoshi/src/tasks/dep-check/index.js
packages/yoshi/test/tasks/dep-check.spec.js

Remove depkeeper for yoshi

---

packages/yoshi/src/loaders/externalize-relative-lodash.js

Fix config for windows
I don't think that this project is tested on windows. if it doesn't break anything it's probably good.

Fix config for windows

---

packages/yoshi/src/utils.js

Same as #459 but also for build time.

Suppress export warnings at build time

---

packages/create-yoshi-app/src/getQuestions.js

In case of missing global user git details, the generator crashed.
...

create-yoshi-app: Fix default global git user config

---

packages/yoshi/config/jest-stylable-transformer.js
packages/yoshi/config/webpack.config.client.js
packages/yoshi/config/webpack.config.specs.js
packages/yoshi/config/webpack.config.storybook.js
packages/yoshi/package.json
packages/yoshi/src/ignore-extensions.js

Upgrade Stylable to use latest @stylable scoped packages, same as #486

Upgrade stylable to new scoped package

---

packages/yoshi/package.json
packages/yoshi/src/tasks/dep-check/index.js
packages/yoshi/test/tasks/dep-check.spec.js

Move depkeeper configuration to depkeeper-preset-yoshi. Left only logging functionality.
Check only logging functionality

Use depkeeper-preset-yoshi

---

packages/yoshi/config/project.js
packages/yoshi/config/webpack.config.client.js
packages/yoshi/package.json
packages/yoshi/test/webpack-config.spec.js

Add TPA-style webpack plugin in order to support tpa styles in SSR.

Add enhanced tpa style webpack plugin

---

packages/yoshi-config/index.js

I was going over `yoshi-config`, these aren't being used anywhere.
All should pass 🍏.

Small cleanup: remove redundant configs

---

packages/yoshi/config/wallaby-mocha.js

Minor change to simplify wallabyCommin.tests update
Existing change should cover this. This is only simplifying the code. No behavioral changes.

simplify wallabyCommon.tests update in wallaby-mocha.js

---

packages/yoshi/src/commands/build.js

Errors generated by `dep-check` are uncaught errors, and this PR handles them properly and exits. Fixes Sentry issue [YOSHI-2D](https://sentry.io/wix_o/yoshi/issues/742362348/?query=is:unresolved).
N/A

handle dep check errors on build

---

.github/stale.yml

Increase stalebot's counter parameters until we're back working on this project in full force.

Increase stalebot's counter params

---

packages/jest-yoshi-preset/package.json
packages/tslint-config-yoshi-base/package.json
packages/tslint-config-yoshi/package.json
packages/yoshi-helpers/package.json
packages/yoshi/package.json

Bump dev dependency to typescript 3

---

packages/yoshi-helpers/utils.js
packages/yoshi/config/webpack.config.js
packages/yoshi/test/webpack-config.spec.js
test-helpers/env-variables.js

extracting artifact id from pom.xml and adding it to the bundle in process env var
testing that bundle holds artifact id in the defined process env var

adds artifact id env var to bundle

---

.travis.yml
website/package.json

Added script to `travis.yml` that release yoshi's website to surge on PR.
...

Release website to surge on PR

---

packages/jest-yoshi-preset/jest-preset.js

Fix watch jest mode - do not watch 'dist' and 'target' folders

---

packages/yoshi/src/tasks/app-server/index.js

properly log port when waiting for server to start

---

packages/create-yoshi-app/templates/client-typescript/__tests__/spec-setup.ts
packages/create-yoshi-app/templates/client-typescript/src/components/App/App.spec.tsx
packages/create-yoshi-app/templates/client-typescript/src/components/App/App.tsx
packages/create-yoshi-app/templates/client-typescript/{%packagejson%}
packages/create-yoshi-app/templates/client/__tests__/spec-setup.js
packages/create-yoshi-app/templates/client/src/components/App/App.js
packages/create-yoshi-app/templates/client/src/components/App/App.spec.js
packages/create-yoshi-app/templates/client/{%packagejson%}
packages/create-yoshi-app/templates/fullstack-typescript/__tests__/spec-setup.ts
packages/create-yoshi-app/templates/fullstack-typescript/src/components/App/App.spec.tsx
packages/create-yoshi-app/templates/fullstack-typescript/src/components/App/App.tsx
packages/create-yoshi-app/templates/fullstack-typescript/{%packagejson%}
packages/create-yoshi-app/templates/fullstack/__tests__/spec-setup.js
packages/create-yoshi-app/templates/fullstack/src/components/App/App.js
packages/create-yoshi-app/templates/fullstack/src/components/App/App.spec.js
packages/create-yoshi-app/templates/fullstack/{%packagejson%}

Replaced testing library from `enzyme` to `react-testing-library` in the following generators:
* `client` 
* `client-typescript`
* `server`
* `server-typescript`
...

replaced enzyme with react-testing-library

---

packages/create-yoshi-app/templates/business-manager-module-typescript/{%packagejson%}
packages/create-yoshi-app/templates/business-manager-module/{%packagejson%}
packages/create-yoshi-app/templates/client-typescript/{%packagejson%}
packages/create-yoshi-app/templates/client/{%packagejson%}
packages/create-yoshi-app/templates/fullstack-typescript/{%packagejson%}
packages/create-yoshi-app/templates/fullstack/{%packagejson%}
packages/create-yoshi-app/templates/server-typescript/{%packagejson%}
packages/create-yoshi-app/templates/server/{%packagejson%}

Update husky && lint-staged use new recommended config format ("husky field in package.json")

---

packages/create-yoshi-app/templates/client/javascript/.vscode/launch.json
packages/create-yoshi-app/templates/client/typescript/.vscode/launch.json
packages/create-yoshi-app/templates/fullstack/javascript/.vscode/launch.json
packages/create-yoshi-app/templates/fullstack/typescript/.vscode/launch.json

Just changed `component` to `spec` in templates VS Code settings and deleted `server` env related configs.

Wrong MATCH_ENV in VS Code settings

---

packages/create-yoshi-app/templates/business-manager-module/javascript/{%packagejson%}
packages/create-yoshi-app/templates/business-manager-module/typescript/{%packagejson%}
packages/create-yoshi-app/templates/out-of-iframe/javascript/test/wix-private.mock.js
packages/yoshi/package.json

bump tpa-style-webpack-plugin to 1.3.6 from 1.3.5 to include a change that we made

bump tpa-style-webpack-plugin

---

packages/yoshi/src/commands/build-app.js

add server bundle on build logs

---

packages/yoshi/bin/yoshi-cli.js
packages/yoshi/src/commands/build-app.js

yoshi: Enable `--source-map` option in app flow build

---

packages/yoshi-config/paths.js
packages/yoshi/src/commands/start-app.js
packages/yoshi/src/server-process.js
packages/yoshi/src/tasks/app-server/index.js

Pipe server output to server.log in app-flow.
Closes #1107 
Tested manually on test project

Pipe output to server.log in app-flow

---

packages/yoshi/package.json

bump tpa-style-webpack-plugin to 1.3.7
...

bump tpa-style-webpack-plugin to 1.3.7

---

packages/create-yoshi-app/templates/client/javascript/src/index.vm
packages/create-yoshi-app/templates/client/javascript/{%packagejson%}
packages/create-yoshi-app/templates/client/typescript/src/index.vm
packages/create-yoshi-app/templates/client/typescript/{%packagejson%}
packages/create-yoshi-app/templates/fullstack/javascript/src/index.ejs
packages/create-yoshi-app/templates/fullstack/javascript/{%packagejson%}
packages/create-yoshi-app/templates/fullstack/typescript/src/index.ejs
packages/create-yoshi-app/templates/fullstack/typescript/{%packagejson%}

This will enable the use of [React Hooks](https://reactjs.org/docs/hooks-intro.html)

Upgrade react to 16.8

---

packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/app/App.js
packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/app/appController.js
packages/create-yoshi-app/templates/out-of-iframe/javascript/src/components/app/appController.spec.js

We've added a Provider component in the `wix-ui-tpa` library, which receives a `mobile` boolean parameter. This should be part of the generator I believe.

add wix-ui-tpa provider - for mobile mode

---

packages/jest-yoshi-preset/package.json

Add types-jest dep for jest autocomplete

---

packages/create-yoshi-app/templates/out-of-iframe/javascript/README.md
packages/create-yoshi-app/templates/out-of-iframe/typescript/README.md

Great stuff!
Just some typo fixes in the README.

OOI README Typos

---

packages/yoshi/config/hot.js
packages/yoshi/config/webpack.config.js
packages/yoshi/src/commands/start-app.js
packages/yoshi/src/server-process.js
packages/yoshi/src/socket-server.js

See title. This is a small improvement since currently, we have a hard-coded port that may already be taken.

Detect an available port for server HMR

---

docs/getting-started/project-types.md

Closes #1375
Add Out Of Iframe project type to Yoshi documentation.

Update docs about project types (add OOI app)

---

packages/yoshi/package.json
packages/yoshi/test/build.spec.js
packages/yoshi/test/loaders.spec.js
renovate.json

Remove lock from webpack version due to this issue that was solved:
https://github.com/webpack/webpack/issues/8656

remove webpack lock from yoshi

---

packages/bootstrap-hot-loader/bootstrap-hot-loader.d.ts
packages/bootstrap-hot-loader/hot.prod.js
packages/bootstrap-hot-loader/index.js
packages/bootstrap-hot-loader/package.json
packages/bootstrap-hot-loader/src/hot.dev.ts
packages/bootstrap-hot-loader/src/hot.prod.ts
packages/bootstrap-hot-loader/src/types.ts
packages/bootstrap-hot-loader/tsconfig.json

Pretty straight-forward. See #1401 for details.

Migrate `bootstrap-hot-loader` to TypeScript

---

packages/yoshi-helpers/src/queries.ts
packages/yoshi/src/commands/lint.js
packages/yoshi/test/lint.spec.js

support eslint for typescript

---

packages/yoshi/config/jest.config.js

Merge local project jest config after default transform
...

jest.config.js - allow overriding transformers from local config

---

docs/guides/svg.md

Paste release notes 
https://wix.github.io/yoshi/blog/2019/03/12/yoshi-4#svgs-as-react-components
into docs

Update SVG usage

---

packages/create-yoshi-app/templates/business-manager-module/typescript/tsconfig.json

Closes #1582 
Existing template tests

Fix BM template by emitting TS src files again

---

packages/yoshi-common/src/webpack.config.ts

Temporary added `thunderbolt-elements` to the whitelisted packages to be transpiled by Yoshi into the server bundle

Temporary webpack.config.ts work around for thunderbolt-elements 

---

packages/create-yoshi-app/templates/flow-bm/typescript/{%packagejson%}
packages/yoshi-flow-bm-runtime/package.json
packages/yoshi-flow-bm/package.json
packages/yoshi-flow-bm/src/bin/yoshi-bm.ts
packages/yoshi-flow-bm/src/createFlowBMModel.ts
packages/yoshi-flow-bm/src/renderModule.ts
packages/yoshi-flow-bm/src/scripts/build.ts
packages/yoshi-flow-bm/src/scripts/start.ts
packages/yoshi-flow-bm/src/webpack.config.ts

Gather all user configuration of the Flow's Model.
Before this PR, the user's configuration was hardcoded for our `flow-bm` template, now it's dynamic.
`flow-bm` template tests.

Extract BM flow's model

---

website/package.json

Remove dependancy to resolve Travis build. 
...

Fix website publishing on master

---

verdaccio.yaml

...
Reduce the noise reported at https://github.com/wix/yoshi/issues/1813
Closes #1813
...
I guess run E2E (but I'm not sure how to)

Reduce verdaccio logger output

---

docs/migration/version-4.md

migration readme - babel config clarification

---

packages/eslint-config-yoshi-base/README.md

After https://github.com/wix/yoshi/pull/1868#issuecomment-576716734 I'm adding the linting guidelines to be part of the readme. It's not the best place but it's better than nothing.
We should probably find a better place in the future

add basic linting guidelines

---

packages/yoshi-flow-monorepo/src/webpack.config.ts

...
Apply content hashes to webworker target output for experimental HTML build

Add content hash to webworker output for experimental build html

---

test/fixtures/javascript/base-template/package.json
test/fixtures/typescript/base-template/package.json
test/javascript/features/entries/package.json
test/javascript/features/externals/package.json
test/javascript/features/hmr/hmr/package.json
test/javascript/features/hmr/web-worker/package.json
test/javascript/features/non-transpiled-externals/transpile-configured-external-javascript/package.json
test/javascript/features/output/output-error-no-client-entry/package.json
test/javascript/features/output/output-error-no-server-entry/package.json
test/javascript/features/tree-shaking/package.json
test/javascript/features/verify-dependencies/package.json
test/javascript/features/web-worker/web-worker-externals/package.json
test/javascript/features/web-worker/web-worker/package.json
test/typescript/features/entries/package.json
test/typescript/features/externals/package.json
test/typescript/features/hmr/hmr/package.json
test/typescript/features/non-transpiled-externals/transpile-configured-external-javascript/package.json
test/typescript/features/non-transpiled-externals/transpile-configured-external-typescript/package.json
test/typescript/features/output/output-error-no-client-entry/package.json
test/typescript/features/output/output-error-no-server-entry/package.json
test/typescript/features/tree-shaking/package.json
test/typescript/features/verify-dependencies/package.json
test/typescript/features/web-worker/web-worker-externals/package.json
test/typescript/features/web-worker/web-worker/package.json

React and react-dom should be externals, as we have in our generators.

Improve test performance

---

packages/create-yoshi-app/templates/out-of-iframe/javascript/{%packagejson%}
packages/create-yoshi-app/templates/out-of-iframe/typescript/{%packagejson%}
packages/yoshi-common/package.json
packages/yoshi-flow-editor-runtime/package.json
packages/yoshi-flow-editor/package.json
yarn.lock

Replace buggy `tpa-style-webpack-plugin@1.3.12` with `tpa-style-webpack-plugin@1.3.13`

bump to tpa-style-webpack-plugin@1.3.13

---

packages/yoshi-flow-monorepo/src/webpack.config.ts

see https://github.com/wix-private/thunderbolt/pull/2600
...
...

Scoping thunderbolt modules under @/wix

---

docs/guides/app-flow.md

Reverts wix/yoshi#2020
After #2051 This can be done 🏆

Revert "Remove ts in index-dev"

---

packages/create-yoshi-app/templates/flow-library/typescript/{%packagejson%}.json

Maybe in the future we'll go with `dev`, but for now let's fall back to the well known `start` and change it all across when we'll have time

Arrange the script in flow library template

---

CODEOWNERS

Remove yurynix from codeowners

---

packages/jest-yoshi-preset/identity-proxy.js
packages/jest-yoshi-preset/jest-preset.js

Closes #2234 
We never tested the actual contents of a css module object, only that it "worked".
I felt it was overkill to test against this, but open to opinions.

Use an identity-proxy that supports both default & named imports

---

packages/create-yoshi-app/templates/flow-library/typescript/tsconfig.json

Those values are enforced by the library flow, See https://github.com/wix/yoshi/pull/2193 for more information.

Fix flow library template tsconfig to support es5 transpilation

---

packages/yoshi-flow-editor/src/model.ts

Import from yoshi-helpers/build

---

packages/yoshi-server-testing/src/index.ts
test/javascript/features/yoshi-server/api-client-server-react/src/components/App/App.spec.js
test/javascript/features/yoshi-server/api-client-server/src/component.spec.js
test/typescript/features/yoshi-server/api-client-server-react/src/components/App/App.spec.tsx
test/typescript/features/yoshi-server/api-client-server/src/component.spec.tsx

We changed the Yoshi Server api - updating Yoshi Server testing accordingly.

Update yoshi server testing with new api

---

packages/yoshi-stylable-dependencies/package.json

We still need to manually update this file with each release. my suggestion is to add ^.

Update stylable to new version

---

website/docs/library-flow.md

Update docs on shipping a `.css` bundle in library-flow

---

website/docs/business-manager-flow.md

This wasn't documented in #2495.
This came up after speaking with @ofiratt which is working on a new project that will use the flow from day 1, so I'm trying to help with issues along the way.

Document `moduleConfigurationId` in bm flow

---

CONTRIBUTING.md

fix(CONTRIBUTING.md): test section typo

---

packages/create-yoshi-app/templates/flow-editor-platform/typescript/src/components/{each%flowData.components:name%each}/viewer.controller.ts
packages/create-yoshi-app/templates/flow-editor-platform/typescript/{%packagejson%}.json
packages/yoshi-flow-editor/package.json
yarn.lock

This change updates `@wix/bob-widget-services` major version
no we will send an object to the widget create method, which will allow it to be more extensible
...

Bump bob-widget-services version

---

website/versioned_docs/version-4.x/development/environment-variables.md

Added `YOSHI_PUBLIC_PATH` documentation
